# Use an official Node runtime as a base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY tsconfig.json ./
COPY .eslintrc.js ./
COPY .prettierrc.json ./
COPY .prettierignore ./

# Install app dependencies
RUN npm install

# Expose port 3000 for the development server
EXPOSE 3000

# Command to run the development server with hot reload
# CMD ["npm", "start"]
