version: "3.9"

x-common-variables: &common-variables
  RUNTIME_ENVIRONMENT: local
  DEBUG: True

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      <<: *common-variables
      # SERVER_HOST has to be 0.0.0.0 to listen to requests from outside container
      SERVER_HOST: 0.0.0.0
    ports:
      - 7900:${SERVER_PORT:-7900}
      - 7901:7901
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
    command: python -m debugpy --listen 0.0.0.0:7901 main.py
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - bridge_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - bridge_network
    environment:
      CHOKIDAR_USEPOLLING: "true" # Enable hot reload with file polling
    command: npm start

  mongodb:
    image: mongo
    container_name: mail-sync-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge
